import {
    FiBookOpen,
    FiCheckSquare,
    FiClock,
    FiCreditCard,
    FiDollarSign,
    FiFileText,
    FiHome,
    FiLogOut,
    FiRepeat,
    FiSettings,
    FiTrendingUp,
    FiUmbrella,
    FiUser,
    FiUserPlus,
    FiUsers,
} from "react-icons/fi";
import { TfiAnnouncement } from "react-icons/tfi";
export const menuItems = [
      {
        code: "dashboard",
        id: "dashboard",
        label: "Dashboard",
        icon: "/images/dashboard.png",
        whiteIcon: "/images/whitedashboard.png",
      },
      {
        code: "onboard",
        id: "onboarding",
        label: "Staff Onboarding",
        icon: "/images/myprofile2.png",
        whiteIcon: "/images/whiteprofile.png",
      },
      {
        code: "attendance",
        id: "attendance",
        label: "Attendance",
        icon: "/images/attendance.png",
        whiteIcon: "/images/whiteattendance.png",
      },
      {
        code: "attendance_management",
        id: "attendance_management",
        label: "Attendance management",
        icon: "/images/attendance.png",
        whiteIcon: "/images/whiteattendance.png",
      },
      {
        code: "task",
        id: "tasks",
        label: "Task Management",
        icon: "/images/task.png",
        whiteIcon: "/images/whitetask.png",
      },
      {
        code: "trainings",
        id: "trainings",
        label: "Trainings",
        icon: "/images/trainings.png",
        whiteIcon: "/images/trainings.png",
      },
      {
        code: "leaves",
        id: "leaves",
        label: "Leave",
        icon: "/images/leave.png",
        whiteIcon: "/images/whiteleave.png",
      },
      {
        code: "pay_slips",
        id: "payslips",
        label: "Pay Slips",
        icon: "/images/payslip.png",
        whiteIcon: "/images/whitepayslip.png",
      },
      {
        code: "digital_cards",
        id: "cards",
        label: "My Cards",
        icon: "/images/digital_cards.png",
        whiteIcon: "/images/digital_cards.png",
      },
      {
        code: "announcements",
        id: "announcements",
        label: "Announcements",
        icon: "/images/announcements.png",
        whiteIcon: "/images/whiteannouncements.png",
      },
      {
        code: "staffcycle",
        id: "staffcycle",
        label: "Staff Cycle",
        icon: "/images/myprofile2.png",
        whiteIcon: "/images/whiteprofile.png",
      },
      {
        code: "employees",
        id: "employees",
        label: "Employees",
        icon: "/images/Frame.png",
        whiteIcon: "/images/Frame.png",
      },
      {
        code: "performance",
        id: "performance",
        label: "Performance",
        icon: "/images/performance.png",
        whiteIcon: "/images/performance.png",
      },
      {
        code: "pay_roll",
        id: "payroll",
        label: "Payroll",
        icon: "/images/payslips.png",
        whiteIcon: "/images/payslips.png",
      },
      {
        code: "my_profile",
        id: "profile",
        label: "My Profile",
        icon: "/images/myprofile2.png",
        whiteIcon: "/images/whiteprofile.png",
      },
      {
        code: "settings",
        id: "settings",
        label: "Settings",
        icon: "/images/settings.png",
        whiteIcon: "/images/settings.png",
      },
 
//   { code: "dashboard", id: "dashboard", label: "Dashboard", icon: FiHome },
//   { code: "onboard", id: "onboarding", label: "Staff Onboarding", icon: FiUserPlus },
//   { code: "attendance", id: "attendance", label: "Attendance", icon: FiClock },
//   { code: "attendance_management", id: "attendance_management", label: "Attendance Management", icon: FiCheckSquare },
//   { code: "task", id: "tasks", label: "Task Management", icon: FiCheckSquare },
//   { code: "trainings", id: "trainings", label: "Trainings", icon: FiBookOpen },
//   { code: "leaves", id: "leaves", label: "Leave", icon: FiUmbrella },
//   { code: "pay_slips", id: "payslips", label: "Pay Slips", icon: FiFileText },
//   { code: "digital_cards", id: "cards", label: "My Cards", icon: FiCreditCard },
//   { code: "announcements", id: "announcements", label: "Announcements", icon: TfiAnnouncement },
//   { code: "staffcycle", id: "staffcycle", label: "Staff Cycle", icon: FiRepeat },
//   { code: "employees", id: "employees", label: "Employees", icon: FiUsers },
//   { code: "performance", id: "performance", label: "Performance", icon: FiTrendingUp },
//   { code: "pay_roll", id: "payroll", label: "Payroll", icon: FiDollarSign },
//   { code: "my_profile", id: "profile", label: "My Profile", icon: FiUser },
//   { code: "settings", id: "settings", label: "Settings", icon: FiSettings },
];

export const logoutIcon = FiLogOut;
